server:
  port: 5050
config:
  sshusername: "user"
  sshhost: "172.31.176.1"
  sshPort: 22
  sshPassword: "test1234"
  databaseUrl: "jdbc:mysql://localhost:3306/mysql"
  databaseId: "root"
  databasePwd: "wjqrmsrma!wl6311"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldothome?useUnicode=true&characterEncoding=utf8
    username: root
    password: wjqrmsrma!wl6311
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace