server:
  port: 8080

file:
  dir: /var/www/html/2021/studentImages/

config:
  sshusername: "multiadmin"
  sshhost: "media.seowon.ac.kr"
  sshPort: 8288
  sshPassword: "ajfxlaleldj"
  databaseUrl: "jdbc:mysql://localhost:3306/mysql"
  databaseId: "root"
  databasePwd: "multi2021"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentDothome?useUnicode=true&characterEncoding=utf8
    username: root
    password : multi2021
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace