spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf8
    username: root
    password : test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace