server:
  port: 3030

file:
  dir: /home/oem/WebDir/2021studentImages/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/s201610309?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace