server:
  port: 2021
file:
  dir: /var/www/html/2021/studentImages/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8
    username: root
    password : multi2021
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace